ARG BASE_IMAGE=go-parallel_queue_exec-base:latest
FROM ${BASE_IMAGE} AS builder

FROM scratch

WORKDIR /bin
COPY --from=builder /bin/app_ws /bin/app_ws
COPY --from=builder /src/config /bin/config

EXPOSE 8080

ENTRYPOINT ["/bin/app_ws"]